"""
Test GPU exception stop reasons from AMD GPU core files.

exception_core.hip launches a kernel that triggers a memory violation.
The core is generated by rocgdb catching the GPU exception signal, then
running gcore to produce a core file. LLDB should report the exception
stop reason with a "Memory access violation" description.
"""

import lldb
from lldbsuite.test.decorators import *
from lldbsuite.test.tools.gpu.amdgpu_core_testbase import AmdGpuCoreTestBase


class TestAmdGpuCoreException(AmdGpuCoreTestBase):
    """Verify GPU exception stop reasons from core files."""

    HIP_SOURCE = "exception_core.hip"
    # The kernel triggers a memory violation — rocgdb will catch the SIGBUS/
    # exception signal and stop. No GPU breakpoint is needed.
    GPU_BREAKPOINT_PATTERN = "// GPU EXCEPTION"

    def _build_rocgdb_script(self, binary, bp_spec, core_path):
        """Override to handle exception-based core generation.

        Instead of setting a GPU breakpoint, we just run the program and
        let rocgdb stop at the GPU exception signal, then gcore.
        """
        commands = [
            "set pagination off",
            "set confirm off",
        ]
        commands.extend(self.ROCGDB_SETUP_COMMANDS)
        commands.extend(
            [
                f"file {binary}",
                "run",
                f"gcore {core_path}",
                "quit",
            ]
        )

        script_path = self.getBuildArtifact("rocgdb_commands.txt")
        with open(script_path, "w") as f:
            f.write("\n".join(commands) + "\n")
        return script_path

    @skipIfRemote
    def test_core_has_gpu_waves(self):
        """Verify exception core loads and has GPU waves."""
        gpu_target, gpu_process = self.load_core()
        self.assertGreater(
            gpu_process.GetNumThreads(),
            0,
            "Exception core should have at least one GPU wave",
        )

    @skipIfRemote
    def test_exception_stop_reason(self):
        """Verify GPU threads report eStopReasonException from core file."""
        gpu_target, gpu_process = self.load_core()

        exception_threads = []
        for i in range(gpu_process.GetNumThreads()):
            thread = gpu_process.GetThreadAtIndex(i)
            if thread.GetStopReason() == lldb.eStopReasonException:
                exception_threads.append(thread)

        self.assertGreater(
            len(exception_threads),
            0,
            "At least one GPU thread should have eStopReasonException",
        )

    @skipIfRemote
    def test_memory_violation_description(self):
        """Verify the exception description contains 'Memory access violation'."""
        gpu_target, gpu_process = self.load_core()

        exception_thread = None
        for i in range(gpu_process.GetNumThreads()):
            thread = gpu_process.GetThreadAtIndex(i)
            if thread.GetStopReason() == lldb.eStopReasonException:
                exception_thread = thread
                break

        self.assertIsNotNone(
            exception_thread, "Should find a thread stopped with an exception"
        )

        stop_description = exception_thread.GetStopDescription(256)
        self.assertIn(
            "Memory access violation",
            stop_description,
            f"Exception description should contain 'Memory access violation', "
            f"got: '{stop_description}'",
        )
